# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Soy Tu Salud' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  
  
  

  # Pods for Soy Tu Salud

end
